# src/indicator_calculator.py

import pandas as pd
import numpy as np

def calculate_indicators(df: pd.DataFrame) -> pd.DataFrame:
    """
    Adds technical indicators to the dataframe.
    Required: Open, High, Low, Close, Volume
    """
    
    # Ensure inputs are floats
    for col in ['Open', 'High', 'Low', 'Close', 'Volume']:
        df[col] = df[col].astype(float)

    # ---------------------------------------------------------
    # 1. MOVING AVERAGES (Trend Strategy)
    # ---------------------------------------------------------
    # Fast MA (10) for short-term trend
    df['Fast_MA'] = df['Close'].rolling(window=10).mean()
    # Slow MA (50) for long-term trend
    df['Slow_MA'] = df['Close'].rolling(window=50).mean()

    # ---------------------------------------------------------
    # 2. RSI (Relative Strength Index)
    # ---------------------------------------------------------
    delta = df['Close'].diff()
    gain = (delta.where(delta > 0, 0)).rolling(window=14).mean()
    loss = (-delta.where(delta < 0, 0)).rolling(window=14).mean()
    
    rs = gain / loss
    df['RSI'] = 100 - (100 / (1 + rs))

    # ---------------------------------------------------------
    # 3. VWAP (Volume Weighted Average Price)
    # ---------------------------------------------------------
    # Typical Price
    df['TP'] = (df['High'] + df['Low'] + df['Close']) / 3
    # Cumulative (Price * Volume) / Cumulative Volume
    # Note: This calculates VWAP based on the loaded data window (5 days)
    df['VWAP'] = (df['TP'] * df['Volume']).cumsum() / df['Volume'].cumsum()

    # ---------------------------------------------------------
    # 4. BOLLINGER BANDS (Volatility Strategy)
    # ---------------------------------------------------------
    # Middle Band = 20 SMA
    df['BB_Middle'] = df['Close'].rolling(window=20).mean()
    # Standard Deviation
    std_dev = df['Close'].rolling(window=20).std()
    # Upper & Lower Bands (2 Std Devs)
    df['BB_Upper'] = df['BB_Middle'] + (2 * std_dev)
    df['BB_Lower'] = df['BB_Middle'] - (2 * std_dev)

    # ---------------------------------------------------------
    # 5. MACD (Momentum Strategy)
    # ---------------------------------------------------------
    # 12 EMA
    ema12 = df['Close'].ewm(span=12, adjust=False).mean()
    # 26 EMA
    ema26 = df['Close'].ewm(span=26, adjust=False).mean()
    
    df['MACD'] = ema12 - ema26
    # Signal Line = 9 EMA of MACD
    df['Signal_Line'] = df['MACD'].ewm(span=9, adjust=False).mean()

    # ---------------------------------------------------------
    # 6. RVOL (Relative Volume)
    # ---------------------------------------------------------
    # Current Volume / Average Volume of last 20 candles
    avg_vol = df['Volume'].rolling(window=20).mean()
    df['RVOL'] = df['Volume'] / avg_vol

    # ---------------------------------------------------------
    # 7. ADX (Average Directional Index) - Optional Trend Strength
    # ---------------------------------------------------------
    # True Range
    df['tr0'] = abs(df['High'] - df['Low'])
    df['tr1'] = abs(df['High'] - df['Close'].shift())
    df['tr2'] = abs(df['Low'] - df['Close'].shift())
    df['TR'] = df[['tr0', 'tr1', 'tr2']].max(axis=1)

    # Directional Movement
    df['up_move'] = df['High'] - df['High'].shift()
    df['down_move'] = df['Low'].shift() - df['Low']
    
    df['plus_dm'] = np.where((df['up_move'] > df['down_move']) & (df['up_move'] > 0), df['up_move'], 0)
    df['minus_dm'] = np.where((df['down_move'] > df['up_move']) & (df['down_move'] > 0), df['down_move'], 0)
    
    # Smooth with 14 period
    window = 14
    df['TR_smooth'] = df['TR'].rolling(window).mean()
    df['plus_dm_smooth'] = df['plus_dm'].rolling(window).mean()
    df['minus_dm_smooth'] = df['minus_dm'].rolling(window).mean()
    
    df['plus_di'] = 100 * (df['plus_dm_smooth'] / df['TR_smooth'])
    df['minus_di'] = 100 * (df['minus_dm_smooth'] / df['TR_smooth'])
    
    df['DX'] = 100 * abs(df['plus_di'] - df['minus_di']) / (df['plus_di'] + df['minus_di'])
    df['ADX'] = df['DX'].rolling(window).mean()

    # ---------------------------------------------------------
    # CLEANUP
    # ---------------------------------------------------------
    # Remove NaN values generated by lookback windows
    # (e.g., the first 50 rows will be NaN because of Slow MA)
    df.dropna(inplace=True)
    
    return df
